# Nixpacks configuration for Railway deployment
# Tells Railway how to build and run the FastAPI backend

[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
