# Render.com Build Configuration
# This file tells Render how to build and run your FastAPI backend

# Build Command: Install dependencies
build_command = pip install -r requirements.txt

# Start Command: Run the FastAPI application
start_command = uvicorn app.main:app --host 0.0.0.0 --port $PORT

# Environment Variables Required in Render Dashboard:
# GROQ_API_KEY=your_actual_groq_api_key_here
# DATABASE_URL=your_postgresql_connection_string
# ALLOWED_ORIGINS=https://your-app.vercel.app,https://health-symptom-predictor.onrender.com,http://localhost:3000
# SECRET_KEY=your-super-secret-jwt-key
# ENVIRONMENT=production
# DEBUG=False
# ADMIN_EMAIL=admin@yourdomain.com
# ADMIN_PASSWORD=your-secure-admin-password

# Auto-Deploy: Enable auto-deploy from main branch
auto_deploy = true
branch = main

# Health Check: Render will check this endpoint
health_check_path = /health

# Service Configuration
service_type = web
runtime = python3.11
region = oregon
